# Generated by Django 4.0.6 on 2022-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_accountmodel_balance_transactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
